### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by evancz** [michaelbjames/elm-benchmark#2]
Goals:
- Have one central library called `Benchmark` that contains all of the basics.
- Combine types, runner, and benchmark. Make LineGraph independent of the Result type. This is primarily so the docs work, but maybe line graphs can be made reusable as well?

I also could not tell what was going on with setup functions. I think these should either be simpler or in some submodule for complex stuff, like `Benchmark.FancySetup` or something.

**Comment by evancz** [comment]
What happened to this?

[This](https://github.com/michaelbjames/elm-benchmark/blob/master/Perf/Benchmark.elm#L23) is not going to be documented. The documentation is extracted from the type signature and comment in that particular file.

I still don't see why there is a `Perf` namespace that everything lives in. Why is it a partial word? What other kind of benchmark is it distinguishing between? Why is the root of `elm-benchmark` not `Benchmark`?

**Comment by evancz** [comment]
I don't think [this](https://github.com/michaelbjames/elm-benchmark/blob/master/Perf/AdvancedBenchmarks.elm#L39) is a well designed API. Rather than require that two lists be the same length, isn't it possible to use one list such that that must be the case? What happens if it is not true? I also don't see why this API should be different than `logicWithDeferredInput` as we discussed yesterday.

It also may help to use names for these type variables longer than one character:

```
logicWithDeferedInput : String -> (input -> output) -> (seed -> input) -> [seed] -> T.Benchmark
```

Also, the T in T.Benchmark is going to show up in the online docs.

**Comment by evancz** [comment]
The inner thunk of [this](https://github.com/michaelbjames/elm-benchmark/blob/master/Perf/Native/Runner.js#L14-L31) is going to be called every time. Should be moved outside if possible.

Why [multiply by 10](https://github.com/michaelbjames/elm-benchmark/blob/master/Perf/Native/Runner.js#L30)?

**Comment by evancz** [comment]
In [this code](https://github.com/michaelbjames/elm-benchmark/blob/master/Perf/Native/Runner.js#L75-L77), why not this:

```
results[bmIndex] =
    { _ : {}
    , name : bms[bmIndex]._0
    , times : []
    };
```

**Comment by evancz** [comment]
Best to keep `index++` outside of a branching structure like [this](https://github.com/michaelbjames/elm-benchmark/blob/master/Perf/Native/Runner.js#L117-L127). Just put it before or after (depending on which one you intend, I'm not sure because this is tricky to read) and if any additional conditions are added you cannot forget to increment `index`.

**Comment by evancz** [comment]
I have heard reasonable arguments against [aligning equals](https://github.com/michaelbjames/elm-benchmark/blob/master/Perf/Native/Runner.js#L176-L180). The idea is that adding a new variable may involve changing _all_ the other definitions to make sure the equals sign still aligns. This leads to a messy diff and makes things harder to take care of.

**Comment by evancz** [comment]
Maybe add `var result = results[bmIndex];` [here](https://github.com/michaelbjames/elm-benchmark/blob/master/Perf/Native/Runner.js#L83)? Not really sure about this, but it feels weird otherwise.

**Comment by evancz** [comment]
[This](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml) seems to be pretty solid advice. It's only applicable to one thing in this code base, but it's something that's good to read even if it's pretty obvious stuff. It gets me into the mindset of writing code that'll last for years.

**Comment by michaelbjames** [comment]
Thanks for all the advice!

Here's a diff of the changes based on the review so far:
https://github.com/michaelbjames/elm-benchmark/compare/4cda8e06f02a29b543900b6b65e216bb9720d33c...43f75a3d99a3c4f66f5983a043f9b84392745804

**Comment by michaelbjames** [comment]
The next round of changes
https://github.com/michaelbjames/elm-benchmark/compare/43f75a3d99a3c4f66f5983a043f9b84392745804...fb6a39acb87bf0fe7af92ab87efa5366e1c1db15

**Comment by evancz** [comment]
Looks great, nice work!
