### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by evancz** [michaelbjames/elm-benchmark#3]
What if it was like this:

```
Benchmark
    logic
    render
    renderStatic
    run

Benchmark.DeferredSetup
    logic
    render
```

With the intention that people import DeferredSetup qualified as DS or something.

**Comment by michaelbjames** [comment]
Okay, I understand this. I suppose that as time goes on and this library gets more complex things will begin to look like:

```
Benchmark
    logic
    render
    run
    …

Benchmark.DeferredSetup
    logic
    render

Benchmark.ThreePhaseSetup
    logic
    render

Benchmark.…
…
```

**Comment by evancz** [comment]
Yeah! :D Or if you expose the underlying `() -> () -> ()` thing, people can create their own depending on what they want. In that world, they can experiment and find the good solution. You can merge it in at some point if that's helpful.

**Comment by evancz** [comment]
Deciding to expose that is probably for a later day though! I think the current deferred approach is fine for nowe.
